# general settings
name: ASFTransformer_nature_physical_turbulence_data
model_type: ImageMlossModel
scale: 1
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 100

# dataset and data loader settings
datasets:
  train:
    name: TrainSet
    type: Turbulence_DATASet
    dataroot_gt: /mnt/data/optimal/zhangziran/dataset/nature_turbdata_p/physical_simulated_videos/train/
    geometric_augs: true

    filename_tmpl: '{}'
    io_backend:
      type: disk

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 8

    mini_batch_sizes: [4]   
    iters: [400000]
    gt_size: 240   
    gt_sizes: [160]
    ### ------------------------------------------------------------

    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: ValSet
    type: Turbulence_DATASet
    dataroot_gt: /mnt/data/optimal/zhangziran/dataset/nature_turbdata/physical_simulated_videos/val/
    io_backend:
      type: disk


# network structures
network_g:
  type: ASFTransformer
  inp_channels: 3
  out_channels: 3
  dim: 48
  num_refinement_blocks: 4
  fbc_expansion_factor: 3
  sbc_expansion_factor: 2.66
  bias: True

# path
path:
  pretrain_network_g: ~ 
  strict_load_g: true
  resume_state: ~

# training settings
train:
  total_iter: 400000
  warmup_iter: 1000 # no warm up -1 
  use_grad_clip: true

  # Split 300k iterations into two cycles. 
  # 1st cycle: fixed 3e-4 LR for 92k iters. 
  # 2nd cycle: cosine annealing (3e-4 to 1e-6) for 208k iters.
  scheduler:
    type: CosineAnnealingRestartCyclicLR
    periods: [92000, 308000]       
    restart_weights: [1,1]
    eta_mins: [0.0003,0.000001]   
  
  mixing_augs:
    mixup: false
    mixup_beta: 1.2
    use_identity: true

  optim_g:
    type: AdamW
    lr: !!float 2e-4
    # 3e-4
    # weight_decay: !!float 1e-4
    betas: [0.9, 0.999]
  
  
  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1
    reduction: mean

  # losses
  flow_opt:
    type: PerceptualLoss
    loss_weight: 0.01
    reduction: mean

  # losses
  phase_opt:
    type: PatchFFTLoss
    loss_weight: 0.1
    reduction: mean

# validation settings
val:
  window_size: 8
  val_freq: !!float 3e4
  save_img: true
  rgb2bgr: false
  use_image: true
  max_minibatch: 8

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    ssim: # metric name, can be arbitrary
      type: calculate_ssim
      crop_border: 0
      test_y_channel: false


# logging settings
logger:
  print_freq: !!float 1e4
  save_checkpoint_freq: !!float 3e4
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
